 version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/online-shop-app
    overwrite: true

permissions:
  - object: scripts/stop_container.sh
    pattern: "*"
    owner: root
    group: root
    mode: 755
  - object: scripts/start_container.sh
    pattern: "*"
    owner: root
    group: root
    mode: 755
  - object: docker_installation.sh
    pattern: "*"
    owner: root
    group: root
    mode: 755

hooks:
  BeforeInstall:
    - location: docker_installation.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
      env:
        PATH: /usr/bin:/usr/local/bin:$PATH

  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
      env:
        PATH: /usr/bin:/usr/local/bin:$PATH
